### ISSUE TITLE
Add Electrical Age Compatibility with Nuclear Tech Mod

### ISSUE THREAD

**Issue by TheVitya2127** [age-series/ElectricalAge#304]
Based on your advice, I suggest making compatibility with this mod, the source code [here](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT )

**Comment by jrddunbr** [comment]
Anything in particular that you want to see added for compat?

Maybe @HbmMods wants to weigh in?

I think based on the gallery of that mod that the best interop would be steam power for our turbines, and maybe some oil processing interop (we can maybe use their fuels)

**Comment by TheVitya2127** [comment]
due to a different fluid system, this will be problematic.  It would be much easier to make a simple HE to Eln converter

**Comment by jrddunbr** [comment]
I don't think we will support HE import directly. Might I suggest making something that creates `steam` in the Forge fluid registry (or maybe ic2 steam / superheated steam?)

**Comment by jrddunbr** [comment]
Note to self: 1HE=4RF

**Comment by TheVitya2127** [comment]
I repeat.  NTM has a different fluid system, not forge.  It is useless to add any liquid converter.

**Comment by TheVitya2127** [comment]
I repeat.  NTM has a different fluid system, not forge.  It is useless to add any liquid converter.

**Comment by TheVitya2127** [comment]
Yes, and there is a steam turbine in NTM. Why craft a second turbine when I had difficulty making an industrial turbine?

**Comment by jrddunbr** [comment]
Have fun!

**Comment by jrddunbr** [comment]
For what it's worth, you will want to look at the code in mods.eln.simple that already do RF/EU conversion. Lmk if you have questions about that.

**Comment by jrddunbr** [comment]
I'm not sure why you think I am worried if you don't want to use the mod. You have the freedom to use whatever mods you want - and to not use Eln if you don't.

I write code for the mod in my free time, and I write the code that I find interesting. It's not my day job lol. I'm happy to give you pointers about the code or maybe even write it myself, but this is a volunteer project. Code gets written because the developers derive enjoyment from working on it. Not because someone whined about it not doing what they wanted.

If you want to write code to do this, I'll help you do it. But, if you want to just complain, I'm going to close the issue.

**Comment by jrddunbr** [comment]
More than half of it is written in a language called Kotlin. They have awesome documentation for it on their website. https://kotlinlang.org/
