### ISSUE TITLE
12.8kV and 51.2kV wiring concept work

### ISSUE THREAD

**Issue by jrddunbr** [age-series/ElectricalAge#73]
@Grissess and I were working on a new idea I had a few weeks back.

I really want to work on having a power system that can do 12.8kV and 51.2kV natively. This means no more down-converting to 3.2kV for breakers and voltage and other stuff.

We have a few ideas about how we're going to do it. There will be a new color tier (purple probably) that does this, and it will have a completely new multiblock style functionality probably based on `TransparentNode`.

These are rough block models, and they will be modeled proper. This was just a set of screenshots to visualize size and shape.

![2019-01-02_01 14 21](https://user-images.githubusercontent.com/14130505/50581943-58a3f200-0e2c-11e9-97e6-c6558613ec0b.png)

## Transformer

The transformer will convert between 12.8kV and 51.2kV (4x).

It can have 1 connection to 51.2kV and up to 3 connections to 12.8kV (for ease of use with a set of T1 poles).

![2019-01-02_01 14 47](https://user-images.githubusercontent.com/14130505/50581938-58a3f200-0e2c-11e9-9508-d5037daf6d54.png)

## Switch Motors (51.2kv)

The breakers and switches will require hydraulic power to move. This hydraulic power must be provided by a shaft power hydraulic pump. The hydraulic pumps are powered from shaft power - you can use either a shaft motor or a turbine of sorts to power this device, which will take signal cable input to control the switch state. Combine with voltage and amperage detection circuits to make an automatic breaker.

The following compressor is the large model - it can power one 51.2kV switch (bigger), or two small 12.8kV switches.

Large shaft power hydraulic pump:
![2019-01-02_01 14 42](https://user-images.githubusercontent.com/14130505/50581939-58a3f200-0e2c-11e9-8079-f863464b0daa.png)

Switch:
![2019-01-02_01 14 39](https://user-images.githubusercontent.com/14130505/50581940-58a3f200-0e2c-11e9-869a-afd62e2d1eaa.png)

If there is a large enough current crossing the switch at the time it's disconnected, you will see an arc. If it's major enough, the phases will cross and if they are not physically separated far enough, cause a arc to cross phases, which will explode the cables outside the substation.

## Small Swtich Motors (12.8kV)

Here's a small switch:
![2019-01-02_01 14 35](https://user-images.githubusercontent.com/14130505/50581941-58a3f200-0e2c-11e9-9665-b6c0ad570dc5.png)

Small shaft power hydraulic pump. Powerful enough for one small switch.
![2019-01-02_01 14 31](https://user-images.githubusercontent.com/14130505/50581942-58a3f200-0e2c-11e9-8b46-7c59b0fb2c4b.png)

## Other tidbits.

Some other things: tall grass too close to cables will catch fire. Fires can cause arcs if they conduct to the ground. You must build the cables at least 3 blocks off the ground, otherwise you can have dangerous arcs to the ground or players. While this won't remove the old Grid Transformer, this will add features that make this system easier and more handy to use for larger installations. The existing Grid Transformer can be useful for smaller installations.

These installations will connect to the existing T2 and T1 poles using a special part that integrates between the rendered cables and the proper block counterparts of the substation. Those are more like rods (technically called bus's)

These wires will not be SixNode compatible (intentionally). They will have to be run on supports where there are no flammable objects. Players will die immediately without arc flash protection (e-coal or chain-mail armor?), animals will die immediately.

If the supports disappear or fall, the cables will hit the ground and arc (think gravel sorta?)

I'm not sure how much current will go across those cables, but my uncle in the industry said that 9A is not uncommon for very high voltage wires that are run between cities.

@Grissess suggested voltage/current measure from hall effect and fiber optic methods. He can elaborate on the technology involved. I also suggested that industry tends to put small wireless transmitters on the cable themselves to detect stress and current in the cable due to various electric fields. Perhaps not in the substations themselves.

I like this image (below) to visualize what we're doing (found it on the net). We only have 2 lines though, since DC. I think at this point, it's reasonable tha 12.8kV and 51.2kV has a ground and live wire, and that disrupting either will cause problems...

![rendering](http://www.distransubstations.com/sites/default/files/library/img/inset-3D.jpg)

PS. You also think that the shaft power based hydraulic pumps could be useful as a high velocity water pump... :)

**Comment by Grissess** [comment]
While mulling this over, and as of reviewing the code base... ELN itself is not ready for _assembled_ multiblock structures. Surely, it does have multiblock structures, like those poles themselves, but they are instantaneously assembled with _one_ item press, not by pattern matching on a large number of blocks in the world. Doing so efficiently seems like it could be difficult, though inspiration might be drawn from other mods which do the same, if they have their source available. (Immersive Engineering comes to mind--again, if that has source...)

For lack of implementing that infrastructure at the moment--and alienating players who are used to assembling large structures with one click--I suggest we make a subset of these devices which are functional, but use the existing infrastructure. We already have the Grid Transformer, and it should be easy to implement:

- transmission breakers: breaks either 12.8kV or 51.2kV. Allows crossconnection of those systems, which will probably cause some grief if you actually do that and close the circuit. In concurrence with Jared, these should require an active power source to open and close, rather than, e.g., just a signal line (though their position can be modulated by a signal line, they still need power to actuate). In addition, they should have a maximum closing/opening velocity (SlewRateLimited), which causes them to not be instantaneous in their connection or disconnection, depending on both the voltage of the system they're carrying, and the present through current--see #75. Additionally, the rate of change should be modulated linearly by their power input, as a fraction of nominal power. This means they notably won't be suitable for "warming up" grid transformers, but would suffice for large network connection and disconnection. (I'm open to the actual duration on this one, e.g., reacting within a nominal half-second for 51.2kV and 1/8th second for 12.8kV should give them ample speed to function as protective devices while not being too unrealistic.)

- transmission probes: like the breakers, can connect to both systems, including problematic cross-connections. They'll function just like the electrical probe, including having mostly the same physical and GUI interface (maybe with different default parameters), except they will be grid-connected. They'll also be much larger than regular probes (think about the size of a Grid Transformer) and should be modeled to reflect that they use "safe" methods of measurement, such as fiber loops.

Additionally, I'd like to focus on #75 in general (which is breaking) in that it will cause cables that cross each-other, or through or near blocks, to short between each other if their potential difference is high enough. (Blocks other than cables are always considered to be grounded.) Furthermore, entities within those areas and in contact with the ground (a boolean known to Minecraft) should also be considered a grounding "fault" path and be essentially vaporized if they cross into this area. Implementation will need a fast spatial set datastructure, which should be achievable. (Most of this should go onto #75 itself.) That way, faults can occur anywhere, not just at these structures. Since breakdown is mostly linear with voltage, I was thinking of ~1m for 12.8kV which implies ~4m for 51.2kV--that's quite a large span, but hopefully encouraged people to _really_ clear out their right-of-ways for transmission towers. Bear in mind that the "transmission breakers" above will interact duly with this system, probably needing to be quite large to span >4m to quench a 51.2kV arc eventually.

**Comment by codgamerMC** [comment]
@jrddunbr I actually love the concept idea that you present, maybe that is exactly what I always wanted to have for ELN, although I know it is a lot of work, my map has evolved to big scales, nothing seems to work for me anymore, cables transmit little power for the voltage, high resistances across distances, lack of proper Transmission Substations with proper breakers for Transmission Systems, T2 Capacity seems alright but T1's 96kW limit seems quite low for my power hungry 2MW system, I recently saw a DEV release you made which now I can have power factors for cables which I pumped to 10 which seems to make everything better, T1 can now transmit almost 1MW , RHV Cables can trans. 150KW 200V Cables can trans. 20kW, and T2 can trans. 4MW which is insane, also the new creative cable is amazing, I've been testing these things now and now I can use breakers without having to use a relay and Signal Processors as "breakers", Although I would love to see Transmission Breakers like in real substations and Bus Bars would be amazing too, as I currently used Hubs for that and now the creative cable, but proper structures would be amazing to see, it will get more "Real" of a Simulation, I leave a picture of what I made as a Transmissions Station that transmits about 500 kW more or less, with proper equipment it would be better, these T2 systems have essentially no breakers, the small breakers are worthless so Signal Processor and relays control the power based on temperature so... Would love to see the implementations!!
![2019-03-07_12 29 57](https://user-images.githubusercontent.com/10374236/53972667-a1e71b00-40d5-11e9-8993-84340166cd8f.png)

**Comment by jrddunbr** [comment]
I should mention that the voltage tiering is going away, so some components of this will change.

Presumably, small grid switches will be used for low current, and the large grid switches for medium current.

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.

**Comment by Grissess** [comment]
Reopened at my request, after some out-of-band conference :)

**Comment by jrddunbr** [comment]
From DennisQt [grid_switch.zip](https://github.com/jrddunbr/ElectricalAge/files/5812203/grid_switch.zip)

**Comment by jrddunbr** [comment]
tbh, this was implemented.
